// Code generated by protoc-gen-go.
// source: protocol/gateinfo.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SCGateInfo struct {
	SrvType          *int32  `protobuf:"varint,1,opt" json:"SrvType,omitempty"`
	SrvId            *int32  `protobuf:"varint,2,opt" json:"SrvId,omitempty"`
	AuthKey          *string `protobuf:"bytes,3,opt" json:"AuthKey,omitempty"`
	Ip               *string `protobuf:"bytes,4,opt" json:"Ip,omitempty"`
	Port             *int32  `protobuf:"varint,5,opt" json:"Port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SCGateInfo) Reset()         { *m = SCGateInfo{} }
func (m *SCGateInfo) String() string { return proto.CompactTextString(m) }
func (*SCGateInfo) ProtoMessage()    {}

func (m *SCGateInfo) GetSrvType() int32 {
	if m != nil && m.SrvType != nil {
		return *m.SrvType
	}
	return 0
}

func (m *SCGateInfo) GetSrvId() int32 {
	if m != nil && m.SrvId != nil {
		return *m.SrvId
	}
	return 0
}

func (m *SCGateInfo) GetAuthKey() string {
	if m != nil && m.AuthKey != nil {
		return *m.AuthKey
	}
	return ""
}

func (m *SCGateInfo) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *SCGateInfo) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func init() {
}
