// Code generated by protoc-gen-go.
// source: protocol/keepalive.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SSPacketKeepAlive struct {
	Flag             *int32 `protobuf:"varint,1,req" json:"Flag,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SSPacketKeepAlive) Reset()         { *m = SSPacketKeepAlive{} }
func (m *SSPacketKeepAlive) String() string { return proto.CompactTextString(m) }
func (*SSPacketKeepAlive) ProtoMessage()    {}

func (m *SSPacketKeepAlive) GetFlag() int32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

func init() {
}
