// Code generated by protoc-gen-go.
// source: protocol/transact.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type TransactStart struct {
	PacketId         *CoreBuiltinPacketID `protobuf:"varint,1,req,enum=protocol.CoreBuiltinPacketID,def=-1000" json:"PacketId,omitempty"`
	MyTNP            *TransactParam       `protobuf:"bytes,2,req" json:"MyTNP,omitempty"`
	ParenTNP         *TransactParam       `protobuf:"bytes,3,req" json:"ParenTNP,omitempty"`
	CustomData       []byte               `protobuf:"bytes,4,opt" json:"CustomData,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *TransactStart) Reset()         { *m = TransactStart{} }
func (m *TransactStart) String() string { return proto.CompactTextString(m) }
func (*TransactStart) ProtoMessage()    {}

const Default_TransactStart_PacketId CoreBuiltinPacketID = CoreBuiltinPacketID_PACKET_SS_TX_START

func (m *TransactStart) GetPacketId() CoreBuiltinPacketID {
	if m != nil && m.PacketId != nil {
		return *m.PacketId
	}
	return Default_TransactStart_PacketId
}

func (m *TransactStart) GetMyTNP() *TransactParam {
	if m != nil {
		return m.MyTNP
	}
	return nil
}

func (m *TransactStart) GetParenTNP() *TransactParam {
	if m != nil {
		return m.ParenTNP
	}
	return nil
}

func (m *TransactStart) GetCustomData() []byte {
	if m != nil {
		return m.CustomData
	}
	return nil
}

type TransactCtrlCmd struct {
	PacketId         *CoreBuiltinPacketID `protobuf:"varint,1,req,enum=protocol.CoreBuiltinPacketID,def=-1001" json:"PacketId,omitempty"`
	TId              *int64               `protobuf:"varint,2,req" json:"TId,omitempty"`
	Cmd              *int32               `protobuf:"varint,3,req" json:"Cmd,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *TransactCtrlCmd) Reset()         { *m = TransactCtrlCmd{} }
func (m *TransactCtrlCmd) String() string { return proto.CompactTextString(m) }
func (*TransactCtrlCmd) ProtoMessage()    {}

const Default_TransactCtrlCmd_PacketId CoreBuiltinPacketID = CoreBuiltinPacketID_PACKET_SS_TX_CMD

func (m *TransactCtrlCmd) GetPacketId() CoreBuiltinPacketID {
	if m != nil && m.PacketId != nil {
		return *m.PacketId
	}
	return Default_TransactCtrlCmd_PacketId
}

func (m *TransactCtrlCmd) GetTId() int64 {
	if m != nil && m.TId != nil {
		return *m.TId
	}
	return 0
}

func (m *TransactCtrlCmd) GetCmd() int32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

type TransactResult struct {
	PacketId         *CoreBuiltinPacketID `protobuf:"varint,1,req,enum=protocol.CoreBuiltinPacketID,def=-1002" json:"PacketId,omitempty"`
	MyTId            *int64               `protobuf:"varint,2,req" json:"MyTId,omitempty"`
	ChildTId         *int64               `protobuf:"varint,3,req" json:"ChildTId,omitempty"`
	RetCode          *int32               `protobuf:"varint,4,req" json:"RetCode,omitempty"`
	CustomData       []byte               `protobuf:"bytes,5,opt" json:"CustomData,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *TransactResult) Reset()         { *m = TransactResult{} }
func (m *TransactResult) String() string { return proto.CompactTextString(m) }
func (*TransactResult) ProtoMessage()    {}

const Default_TransactResult_PacketId CoreBuiltinPacketID = CoreBuiltinPacketID_PACKET_SS_TX_RESULT

func (m *TransactResult) GetPacketId() CoreBuiltinPacketID {
	if m != nil && m.PacketId != nil {
		return *m.PacketId
	}
	return Default_TransactResult_PacketId
}

func (m *TransactResult) GetMyTId() int64 {
	if m != nil && m.MyTId != nil {
		return *m.MyTId
	}
	return 0
}

func (m *TransactResult) GetChildTId() int64 {
	if m != nil && m.ChildTId != nil {
		return *m.ChildTId
	}
	return 0
}

func (m *TransactResult) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *TransactResult) GetCustomData() []byte {
	if m != nil {
		return m.CustomData
	}
	return nil
}

type TransactParam struct {
	TransNodeID      *int64 `protobuf:"varint,1,req" json:"TransNodeID,omitempty"`
	TransType        *int32 `protobuf:"varint,2,req" json:"TransType,omitempty"`
	OwnerType        *int32 `protobuf:"varint,3,req" json:"OwnerType,omitempty"`
	OwnerID          *int32 `protobuf:"varint,4,req" json:"OwnerID,omitempty"`
	SkeletonID       *int32 `protobuf:"varint,5,req" json:"SkeletonID,omitempty"`
	LevelNo          *int32 `protobuf:"varint,6,req" json:"LevelNo,omitempty"`
	AreaID           *int32 `protobuf:"varint,7,req" json:"AreaID,omitempty"`
	TimeOut          *int64 `protobuf:"varint,8,req" json:"TimeOut,omitempty"`
	TransCommitType  *int32 `protobuf:"varint,9,req" json:"TransCommitType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TransactParam) Reset()         { *m = TransactParam{} }
func (m *TransactParam) String() string { return proto.CompactTextString(m) }
func (*TransactParam) ProtoMessage()    {}

func (m *TransactParam) GetTransNodeID() int64 {
	if m != nil && m.TransNodeID != nil {
		return *m.TransNodeID
	}
	return 0
}

func (m *TransactParam) GetTransType() int32 {
	if m != nil && m.TransType != nil {
		return *m.TransType
	}
	return 0
}

func (m *TransactParam) GetOwnerType() int32 {
	if m != nil && m.OwnerType != nil {
		return *m.OwnerType
	}
	return 0
}

func (m *TransactParam) GetOwnerID() int32 {
	if m != nil && m.OwnerID != nil {
		return *m.OwnerID
	}
	return 0
}

func (m *TransactParam) GetSkeletonID() int32 {
	if m != nil && m.SkeletonID != nil {
		return *m.SkeletonID
	}
	return 0
}

func (m *TransactParam) GetLevelNo() int32 {
	if m != nil && m.LevelNo != nil {
		return *m.LevelNo
	}
	return 0
}

func (m *TransactParam) GetAreaID() int32 {
	if m != nil && m.AreaID != nil {
		return *m.AreaID
	}
	return 0
}

func (m *TransactParam) GetTimeOut() int64 {
	if m != nil && m.TimeOut != nil {
		return *m.TimeOut
	}
	return 0
}

func (m *TransactParam) GetTransCommitType() int32 {
	if m != nil && m.TransCommitType != nil {
		return *m.TransCommitType
	}
	return 0
}

func init() {
}
