// Code generated by protoc-gen-go.
// source: protocol/multicast.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SSPacketMulticast struct {
	Sessions         []*MCSessionUnion `protobuf:"bytes,1,rep" json:"Sessions,omitempty"`
	PacketId         *int32            `protobuf:"varint,2,req" json:"PacketId,omitempty"`
	Data             []byte            `protobuf:"bytes,3,req" json:"Data,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *SSPacketMulticast) Reset()         { *m = SSPacketMulticast{} }
func (m *SSPacketMulticast) String() string { return proto.CompactTextString(m) }
func (*SSPacketMulticast) ProtoMessage()    {}

func (m *SSPacketMulticast) GetSessions() []*MCSessionUnion {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func (m *SSPacketMulticast) GetPacketId() int32 {
	if m != nil && m.PacketId != nil {
		return *m.PacketId
	}
	return 0
}

func (m *SSPacketMulticast) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MCSessionUnion struct {
	Mccs             *MCClientSession `protobuf:"bytes,1,opt" json:"Mccs,omitempty"`
	Mcss             *MCServerSession `protobuf:"bytes,2,opt" json:"Mcss,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MCSessionUnion) Reset()         { *m = MCSessionUnion{} }
func (m *MCSessionUnion) String() string { return proto.CompactTextString(m) }
func (*MCSessionUnion) ProtoMessage()    {}

func (m *MCSessionUnion) GetMccs() *MCClientSession {
	if m != nil {
		return m.Mccs
	}
	return nil
}

func (m *MCSessionUnion) GetMcss() *MCServerSession {
	if m != nil {
		return m.Mcss
	}
	return nil
}

type MCClientSession struct {
	SId              *int64 `protobuf:"varint,1,req" json:"SId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MCClientSession) Reset()         { *m = MCClientSession{} }
func (m *MCClientSession) String() string { return proto.CompactTextString(m) }
func (*MCClientSession) ProtoMessage()    {}

func (m *MCClientSession) GetSId() int64 {
	if m != nil && m.SId != nil {
		return *m.SId
	}
	return 0
}

type MCServerSession struct {
	SArea            *int32 `protobuf:"varint,1,req" json:"SArea,omitempty"`
	SType            *int32 `protobuf:"varint,2,req" json:"SType,omitempty"`
	SId              *int32 `protobuf:"varint,3,req" json:"SId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MCServerSession) Reset()         { *m = MCServerSession{} }
func (m *MCServerSession) String() string { return proto.CompactTextString(m) }
func (*MCServerSession) ProtoMessage()    {}

func (m *MCServerSession) GetSArea() int32 {
	if m != nil && m.SArea != nil {
		return *m.SArea
	}
	return 0
}

func (m *MCServerSession) GetSType() int32 {
	if m != nil && m.SType != nil {
		return *m.SType
	}
	return 0
}

func (m *MCServerSession) GetSId() int32 {
	if m != nil && m.SId != nil {
		return *m.SId
	}
	return 0
}

func init() {
}
